### ISSUE TITLE
email spam?

### ISSUE THREAD

**Issue by benjamingr** [ponicode/ponicode.github.io#4]
Hi,

I've received an email I don't recall signing up for with no way to reply from "Robert from the Git Info team":

![image](https://user-images.githubusercontent.com/1315533/131851948-abddc2ca-7094-4015-976b-5944cac6bb9b.png)

It is advertising this product. Please put my mind at ease by contacting me (my email is in the node main repo readme, which is probably where Robert got it in the first place) and telling me when/how I signed up.

Not only is unsolicited marketing emails highly illegal in my jurisdiction - it is also abuse of the VSCode marketplace terms of service. As you know my employer (Microsoft) takes abuse and privacy very seriously.

Of course - if I did consent and forgot - humble apologies - I am posting this issue to give you the benefit of the doubt and explain.

I would have sent an email but there was no "return address" to email and all the guesses I tried when replying to the email returned "address not found".

**Comment by dwjohnston** [comment]
Yeah I received a github pull request advertising their products. Github's spam filters seemed to have pulled it down. 

![spammy email](https://i.imgur.com/WCHI9GL.png) 

These guys seem like cowboys.

**Comment by benjamingr** [comment]
Oh I forgot about this. Going to give one last ping to @wbenbihi @MelodiousThonk @Myushu @pierrevdk before escalating this to the VSCode team and reporting these accounts to GitHub internally for abuse since that sort of escalation seems kind of harsh but then again so is spamming people and then ignoring them.

**Comment by wbenbihi** [comment]
Hi @benjamingr,

I am surprised to see my name on this topic while I am not affiliated to Ponicode anymore.

You can contact them directly if you need. Would you please stop tagging me on these issues?

Thank you for your time

**Comment by benjamingr** [comment]
> You can contact them directly if you need. Would you please stop tagging me on these issues?

Who is the right contact?

**Comment by bbouffaut** [comment]
Hello @benjamingr . Many thanks for your message and sorry for the late answer.

I'm very surprised about the email you received. We usually don't send such kind of message. We will investigate to identify where it comes from.

I really want to apologize for this and hope it will not affect the image of Ponicode in your experienced developer' eyes.

Don't hesitate to contact me in PM if you wish.

BR,
Baptiste.

**Comment by hsandt** [comment]
I also received the same email on October 13.

Considering it was sent by the so-called "Git Info team" or "The JS Tips Team" (in the From field) and mentions 2 different plugins, it seems unrelated to the Ponicode team. Sounds like some entity is promoting those two plugins without the author's permission.

Which could be a thing (for instance GitHub could send a monthly highlight of the new repositories with the most stars). In this case the sentences seem original, so it really seems like a third-party mentioning cool tools they found, not a bot copy-pasting a generic description.

The issue is:
* we never subscribed to git-info
* the links in the email are dead, at least today, including the Unsubscribe link (mailtrain.ponicode.com:3004/links/... says "site can't be reached" - I tried it because I have a JS blocker, but you can do a simple ping mailtrain.ponicode.com to test it safely)
* the links point at Ponicode specifically while the rest of the message assumes a third-party
* I couldn't find any info on the so-called Git Info team nor The JS Tips Team except an eponymous team on GitHub that just happens to collect JS tips on their repo (but not send email a priori).

I would have said it was either a phishing attempt with real content (rare?!) or unsollicited marketing for the Git Info team itself ("cool, I want to follow more of their tips by actually subscribing for more!") if the links were not using the ponicode.com domain, and there was a way to actually go to their website...

Since anybody could put invalid links in their email, I'll keep considering them as unrelated third-party with bad newsletter practice and email generation, and filter them as spam should they send another one.

**Comment by strayer** [comment]
<img width="686" alt="grafik" src="https://user-images.githubusercontent.com/310624/141824389-73182d1b-0a2f-42da-89b2-f4e50e41f4d2.png">

I received this today. The unsubscribe-link seems to go to https://www.git-info.com/unsubscribe, clearly just pretending to unsubscribe the user.

In case the Ponicode team wants to investigate this, feel free to contact me via the email you got at privacy@ponicode.com earlier.

**Comment by benjamingr** [comment]
@bbouffaut ^

**Comment by strayer** [comment]
@bbouffaut I tried to contact you directly on Twitter, but it seems you disabled direct messages. Where can I contact you, as you proposed earlier in this issue?

**Comment by strayer** [comment]
In case anyone was wondering, the Netlify fraud team suspended git-info.com. There is a snapshot in the wayback machine if someone wants to check it out: https://web.archive.org/web/20211115184050/https://www.git-info.com/

**Comment by 0biWanKenobi** [comment]
This keeps happening:
![image](https://user-images.githubusercontent.com/4061104/142162238-1537aa4b-7e84-49ac-ae85-66c86cb67c34.png)

the unsubscribe link points to http://mailtrain.ponicode.com:3004/links/mdQpsrVsLw/WbvXnWsLnR/dQeYvBujkr/ZGIsRgGVGU

**Comment by benjamingr** [comment]
https://marketplace.visualstudio.com/items?itemName=ponicode.ponicode You go to the VSCode extension and press report abuse, then send an email to vsmarketplace@microsoft.com (with the format suggested) and explain the email spam.

@0biWanKenobi @strayer

**Comment by strayer** [comment]
@0biWanKenobi also make sure to report to AWS because they are using SES: https://aws.amazon.com/de/premiumsupport/knowledge-center/report-aws-abuse/

**Comment by benjamingr** [comment]
I think 2 months is more than enough so I just reported the issue internally from my @microsoft email address. If that doesn't work I'll go through my dev-rel contacts and friends who work on code.

**Comment by bbouffaut** [comment]
Hello everyone. Many thanks for your messages.

As previously mentioned, those emails don't come from us. We didn't manage to find who is doing that.

I understand you are exasperated by this, but is it not over-exaggerated to ask people to report our extension as abused ? Our product tries to help developers. I think this is not at all an abusive product.

We will continue the investigations to identify who is trying to attack our brand and image.I really want to apologize about that.

BR,
Baptiste.

**Comment by strayer** [comment]
To be clear, I didn't mean to say report Ponicode to AWS but the spam e-mail, as it was sent via SES. Netlify confirmed to me that the git-info.com site was apparently not affiliated with Ponicode, but I can't avoid being suspicious considering *all* links in the e-mail went to http://mailtrain.ponicode.com:3004/ and git-info.com was registered by someone in ile de france. Could be a coincidence, obviously.

Anyways, I do believe you. I hope you can find out who or what caused this. As a developer centric service this kind of marketing can really only backfire.

**Comment by dwjohnston** [comment]
@bbouffaut  Note also PRs as a vector of spam. Unfortunately the PR has since been removed, so I'm not sure which account it actually came from.

**Comment by benjamingr** [comment]
> I understand you are exasperated by this, but is it not over-exaggerated to ask people to report our extension as abused ? Our product tries to help developers. I think this is not at all an abusive product.

So you are claiming that the emails that are mostly advertising ponicode (and not much else) are coming from a third-party that is not affiliated with you and has just decided to advertise your commercial product out of generosity? That you are unable to stop this benefactor?

**Comment by 0biWanKenobi** [comment]
> That you are unable to stop this benefactor?

my 2 cents: it is in fact impossible to stop anyone from putting a link in an email and send it. 

If - as we all hope - Ponicode is innocent in this matter, there is not much they can do other than report to Netlify / AWS / whatever. Next day the spammers will move to another service to send automated emails, rinse and repeat. This is something that, imho, should be handed to the relevant authorities. I might be wrong of course, just my opinion.

**Comment by benjamingr** [comment]
Hi, no need to report this further to the VSCode marketplace team. I have contacted them using my @microsoft address and are taking a look at this. If anyone has any additional information (many example spam/abuse emails for example) feel free to send it their way.
